# Development Docker Compose configuration file
#
# How to run:
# docker compose -f ./docker-compose.dev.yaml up -d --build
#
# Author: Osvaldo Hernandez-Segura
#
# Date Created: January 22, 2026
#
# Last Modified: January 23, 2026
#
# References: Copilot, ChatGPT, Docker Documentation

services:
  ml-inference-service:
    build:
      context: ./services/ml_inference/
      dockerfile: Dockerfile.dev
    container_name: ml_inference_service_dev
    env_file: 
      - ./services/ml_inference/src/.env
    environment:
      - HOST=0.0.0.0
      - MODEL_PATH=/app/src/models/linear_svc_pipeline_v1.joblib
      - LABEL_ENCODR_PATH=/app/src/models/articles-bypublisher_LabelEncoder_v1.joblib
      - INTERNAL_API_KEY=/app/secrets/INTERNAL_API_KEY.txt
    expose:
      - "5020"
    volumes:
      - ./services/ml_inference/src/models/:/app/src/models/:ro
      - ./services/ml_inference/secrets/:/app/secrets/:ro

  server:
    build:
      context: ./web_app/
      dockerfile: ./server/Dockerfile.dev
    container_name: web_app_server_dev
    env_file: 
      - ./web_app/server/.env
    environment:
      - INFERENCE_API_URL=http://ml-inference-service:5020
      - INFERERENCE_API_KEY=/app/secrets/INTERNAL_API_KEY.txt
    ports:
      - "3000:3000"
    volumes:
      - ./services/ml_inference/secrets/:/app/secrets/:ro
    depends_on:
      - ml-inference-service

